"""phase5_persistence_tables

Revision ID: 61e4cc02b3f3
Revises: a1ae32b22ca8
Create Date: 2026-08-13 07:47:34.022047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61e4cc02b3f3'
down_revision: Union[str, Sequence[str], None] = 'a1ae32b22ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.String(), nullable=False),
    sa.Column('current_question_id', sa.String(), nullable=True),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('followups_used', sa.Integer(), nullable=False),
    sa.Column('background_questions_asked', sa.Integer(), nullable=False),
    sa.Column('competencies_evaluated', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_remaining_seconds', sa.Integer(), nullable=False),
    sa.Column('last_message_sequence', sa.Integer(), nullable=False),
    sa.Column('last_event_sequence', sa.Integer(), nullable=False),
    sa.Column('current_question_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('section_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_number', name='uq_event_session_seq')
    )
    op.create_table('interview_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_number', name='uq_message_session_seq')
    )
    op.add_column('interview_sessions', sa.Column('active_agent_id', sa.String(), nullable=True))
    op.add_column('interview_sessions', sa.Column('agent_lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'agent_lease_expires_at')
    op.drop_column('interview_sessions', 'active_agent_id')
    op.drop_table('interview_messages')
    op.drop_table('interview_events')
    op.drop_table('interview_checkpoints')
    # ### end Alembic commands ###
