"""phase_3_rbac

Revision ID: 8e55ee7764a7
Revises: e406d842fc72
Create Date: 2026-08-21 10:11:08.310576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e55ee7764a7'
down_revision: Union[str, Sequence[str], None] = 'e406d842fc72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('supabase_user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'candidate_profiles', ['supabase_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_profiles', type_='unique')
    op.drop_column('candidate_profiles', 'supabase_user_id')
    # ### end Alembic commands ###
