"""add override_suggested and override_reason to evaluations

Revision ID: f4f1cb53b84c
Revises: d1f4a8c93b21
Create Date: 2026-08-31 09:55:41.853076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f1cb53b84c'
down_revision: Union[str, Sequence[str], None] = 'd1f4a8c93b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('override_suggested', sa.Boolean(), nullable=True))
    op.add_column('evaluations', sa.Column('override_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'override_reason')
    op.drop_column('evaluations', 'override_suggested')
    # ### end Alembic commands ###
