"""Add question_records to InterviewCheckpoint

Revision ID: f805bc0de0ff
Revises: 26ed14af3bd1
Create Date: 2026-08-17 08:47:04.411733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f805bc0de0ff'
down_revision: Union[str, Sequence[str], None] = '61e4cc02b3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_checkpoints', sa.Column('question_records', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_checkpoints', 'question_records')
    # ### end Alembic commands ###
