"""Generate the documentation that would otherwise go stale (H6-B).

Two files are produced from the code rather than maintained by hand:

    docs/handover/env-matrix.md    every setting, from the Settings classes
    docs/technical/data-model.md   every table, from the SQLAlchemy models

Both were previously written by hand and both had drifted badly --
`data-model.md` named three tables that do not exist and omitted fifteen
that do. A generated file cannot drift, and `backend/tests/test_docs.py`
fails when the checked-in copy no longer matches the code, so drift is a
red build rather than a surprise during a handover.

    python scripts/generate_docs.py           # write the files
    python scripts/generate_docs.py --check   # fail if they are stale

Settings documentation comes from the attribute docstrings in the Settings
classes, read with `ast` -- pydantic does not expose them unless
`use_attribute_docstrings` is enabled, and turning that on would change
the OpenAPI schema for every model in the project.
"""
from __future__ import annotations

import argparse
import ast
import os
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BACKEND = REPO / "backend"
AGENT = REPO / "agent"

ENV_MATRIX = REPO / "docs" / "handover" / "env-matrix.md"
DATA_MODEL = REPO / "docs" / "technical" / "data-model.md"

BANNER = "<!-- Generated by scripts/generate_docs.py. Do not edit by hand; edit the code and re-run. -->"


# ── settings ──────────────────────────────────────────────────────────────

@dataclass
class Setting:
    name: str
    annotation: str
    default: str | None
    doc: str

    @property
    def required(self) -> bool:
        return self.default is None


def _unparse(node: ast.AST | None) -> str | None:
    if node is None:
        return None
    text = ast.unparse(node)
    # Field(default=...) and Field(default_factory=...) both mean "has one".
    if text.startswith("Field("):
        for key in ("default=", "default_factory="):
            if key in text:
                return text
        return None
    return text


def read_settings(path: Path, class_name: str) -> list[Setting]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    cls = next(
        node for node in ast.walk(tree)
        if isinstance(node, ast.ClassDef) and node.name == class_name
    )
    settings: list[Setting] = []
    body = cls.body
    for index, node in enumerate(body):
        if not (isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name)):
            continue
        name = node.target.id
        if name.startswith("_") or name == "model_config":
            continue
        following = body[index + 1] if index + 1 < len(body) else None
        doc = ""
        if (
            isinstance(following, ast.Expr)
            and isinstance(following.value, ast.Constant)
            and isinstance(following.value.value, str)
        ):
            doc = " ".join(following.value.value.split())
        settings.append(
            Setting(name=name, annotation=ast.unparse(node.annotation), default=_unparse(node.value), doc=doc)
        )
    return settings


def read_frontend_keys() -> list[tuple[str, str]]:
    """The browser app's keys and their one-line comments, from its
    .env.example -- there is no Settings class on that side."""
    out: list[tuple[str, str]] = []
    for line in (REPO / "frontend" / ".env.example").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line.startswith("VITE_"):
            continue
        assignment, _, comment = line.partition("#")
        key = assignment.split("=", 1)[0].strip()
        out.append((key, comment.strip()))
    return out


def _cell(text: str) -> str:
    return text.replace("|", r"\|").replace("\n", " ")


def render_env_matrix() -> str:
    backend = read_settings(BACKEND / "backend" / "core" / "config.py", "Settings")
    agent = read_settings(AGENT / "agent" / "config.py", "AgentSettings")

    lines = [
        BANNER,
        "",
        "# Environment matrix",
        "",
        "Every setting the three services read, where it comes from and what",
        "happens if it is missing. Generated from the `Settings` classes, so it",
        "cannot drift from the code; `backend/tests/test_docs.py` fails if this",
        "file is out of date.",
        "",
        "**Required** means there is no default: the process will not start",
        "without it. Settings marked **fail-closed** have a default that is",
        "refused outside `ENVIRONMENT=local|test` -- a placeholder secret or a",
        "development CORS origin stops a production boot rather than serving",
        "with it (`backend/backend/core/config.py`).",
        "",
        "Local values live in the repo-root `.env`; the container stack reads",
        "the same file (`docs/handover/deploy.md`).",
        "",
    ]

    fail_closed = {
        "SECRET_KEY", "AGENT_API_SECRET", "LIVEKIT_URL", "LIVEKIT_API_KEY",
        "LIVEKIT_API_SECRET", "BACKEND_CORS_ORIGINS",
    }

    for title, group, note in (
        ("Backend (`backend.main`)", backend,
         "Read by the API and the one-shot `migrate` container."),
        ("Agent worker (`agent.main`)", agent,
         "Read by the LiveKit worker. It never talks to the database directly; "
         "`AGENT_API_SECRET` and `BACKEND_INTERNAL_URL` are how it reaches the backend."),
    ):
        lines += [f"## {title}", "", note, "",
                  "| Setting | Type | Default | Notes |", "|---|---|---|---|"]
        for setting in group:
            if setting.required:
                default = "**required**"
            elif setting.name in fail_closed:
                default = f"`{setting.default}` — **fail-closed**"
            else:
                default = f"`{setting.default}`"
            lines.append(
                f"| `{setting.name}` | `{_cell(setting.annotation)}` | {_cell(default)} | {_cell(setting.doc)} |"
            )
        lines.append("")

    lines += [
        "## Browser app (built into the bundle, or injected at run time)", "",
        "In production these are **not** baked in: the `web` image writes",
        "`/config.js` from its environment at start-up, so one image runs",
        "everywhere (`docs/handover/deploy.md`). Everything here reaches the",
        "browser — put nothing secret in it.", "",
        "| Setting | Notes |", "|---|---|",
    ]
    for key, comment in read_frontend_keys():
        lines.append(f"| `{key}` | {_cell(comment)} |")
    lines.append("")

    required = [s.name for s in backend + agent if s.required]
    lines += [
        "## The short list", "",
        "A deployment needs at minimum these, which have no default at all:", "",
    ] + [f"- `{name}`" for name in required] + [
        "",
        "...plus the fail-closed set above, which has defaults that production",
        "refuses: " + ", ".join(f"`{name}`" for name in sorted(fail_closed)) + ".",
        "",
    ]
    return "\n".join(lines)


# ── data model ────────────────────────────────────────────────────────────

PERSONAL_DATA = {
    "candidate_profiles": "name, email, and the CV-derived profile",
    "resumes": "CV filename, storage key and extracted text",
    "interview_messages": "everything the candidate said",
    "interview_checkpoints": "conversation state, including transcript fragments",
    "interview_events": "what happened during the interview",
    "evaluations": "the assessment of a person",
    "scores": "per-criterion assessment of a person",
    "interview_invitations": "a candidate's email address",
    "interview_consents": "what the candidate agreed to, and when",
    "admin_audit_log": "who did what to the above",
}


def render_data_model() -> str:
    os.environ.setdefault("DATABASE_URL", "postgresql+asyncpg://postgres:postgres@127.0.0.1:5433/himma_test")
    sys.path.insert(0, str(BACKEND))
    import backend.db.base  # noqa: F401 -- registers every model
    from backend.db.session import Base

    lines = [
        BANNER,
        "",
        "# Data model",
        "",
        "Generated from the SQLAlchemy models, which are the source of truth —",
        "the Alembic chain builds exactly this. The hand-written version of this",
        "file named three tables that had never existed and omitted fifteen that",
        "did, which is why it is generated now.",
        "",
        "`docs/BASELINE_SCHEMA.md` is the Phase-0 snapshot and is deliberately",
        "**not** updated: it records where the schema started.",
        "",
        "Tables holding personal data are marked 🔒 and are listed with what",
        "deletes them in `docs/handover/security.md` §3.",
        "",
        f"**{len(Base.metadata.tables)} tables.**",
        "",
    ]

    for name in sorted(Base.metadata.tables):
        table = Base.metadata.tables[name]
        mark = " 🔒" if name in PERSONAL_DATA else ""
        lines += [f"## `{name}`{mark}", ""]
        if name in PERSONAL_DATA:
            lines += [f"Personal data: {PERSONAL_DATA[name]}.", ""]
        lines += ["| Column | Type | Null | Default | References |", "|---|---|---|---|---|"]
        for column in table.columns:
            refs = ""
            for fk in column.foreign_keys:
                ondelete = f" `ON DELETE {fk.ondelete}`" if fk.ondelete else ""
                refs = f"`{fk.target_fullname}`{ondelete}"
            default = ""
            if column.server_default is not None:
                text = getattr(column.server_default, "arg", "")
                default = f"`{str(text).strip()}`"
            elif column.default is not None:
                default = "_(application)_"
            lines.append(
                f"| `{column.name}` | `{column.type}` | {'yes' if column.nullable else 'no'} | {default} | {refs} |"
            )
        indexes = sorted(index.name for index in table.indexes)
        if indexes:
            lines += ["", "Indexes: " + ", ".join(f"`{i}`" for i in indexes)]
        lines.append("")

    return "\n".join(lines)


# ── entry ─────────────────────────────────────────────────────────────────

TARGETS = ((ENV_MATRIX, render_env_matrix), (DATA_MODEL, render_data_model))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if a file is out of date instead of writing it")
    args = parser.parse_args(argv)

    stale = []
    for path, render in TARGETS:
        content = render().rstrip("\n") + "\n"
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                stale.append(path.relative_to(REPO).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO).as_posix()}")

    if stale:
        print("Out of date: " + ", ".join(stale))
        print("Run: python scripts/generate_docs.py")
        return 1
    if args.check:
        print("Generated documentation is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
